name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [ published ]

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Install libuv
      run: sudo apt-get update && sudo apt-get install -y libuv1-dev
    - name: Setup Scala
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '17'
        check-latest: true
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: Cache Dependencies
      uses: coursier/cache-action@v6
    - name: Check all code compiles
      run: sbt +Test/compile
    - name: Check artifacts build process
      run: sbt +publishLocal
    - name: Compile examples
      run: sbt compileExamples
    - name: Mima check
      run: sbt mimaChecks
    - name: Undeclared dependencies check
      run: sbt undeclaredCompileDependencies
    - name: Unused dependencies check
      run: sbt unusedCompileDependenciesTest
    - name: MissingLink
      run: sbt missinglinkCheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Install libuv
      run: sudo apt-get update && sudo apt-get install -y libuv1-dev
    - name: Setup Scala
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '17'
        check-latest: true
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: Cache Dependencies
      uses: coursier/cache-action@v6
    - name: Lint
      run: sbt check

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
        - '11'
        - '17'
        - '21'
    steps:
    - name: Install libuv
      run: sudo apt-get update && sudo apt-get install -y libuv1-dev
    - name: Setup Scala
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: ${{ matrix.java }}
        check-latest: true
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: Cache Dependencies
      uses: coursier/cache-action@v6
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Test
      run: sbt +test

  ci:
    name: ci
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    - build
    steps:
    - name: Report Successful CI
      run: echo "ci passed"

  release:
    name: Release
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs:
    - ci
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Install libuv
      run: sudo apt-get update && sudo apt-get install -y libuv1-dev
    - name: Setup Scala
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '17'
        check-latest: true
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: Cache Dependencies
      uses: coursier/cache-action@v6
    - name: Release
      run: sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_CREDENTIAL_HOST: central.sonatype.com
